implements initial integration of alfred as start up helper

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,51 +1,21 @@
 #!/bin/bash
 
-LOCAL_VOLUME_POSTGRES=./postgres-data
-LOCAL_VOLUME_MINIO=./minio-data
-LOCAL_VOLUME_QDRANT=./qdrant-storage
+docker-compose -f alfred-docker-compose.yml up -d
 
+echo "Preparing refinery..."
 
-unameOut="$(uname -s)"
-case "${unameOut}" in
-    Linux*)     HOST_IP=$(ip a | grep "inet " | grep -v 127.0.0.1 | head -1 | grep -o -E "[0-9]+.[0-9]+.[0-9]+.[0-9]+" | head -1);;
-    Darwin*)    HOST_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | grep -o -E "[0-9]+.[0-9]+.[0-9]+.[0-9]+" | head -1);;
-esac
+MINIO_ENDPOINT=$(curl -X GET -s 'http://localhost:7066/start')
+while [ $? -ne 0 ]
+do
+    MINIO_ENDPOINT=$(curl -X GET -s 'http://localhost:7066/start')
+done
 
-CREDENTIAL_IP=$(docker network inspect bridge --format='{{json .IPAM.Config}}' | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | tail -1)
-
-MINIO_ENDPOINT="http://$HOST_IP:7053"
-CRED_ENDPOINT="http://$CREDENTIAL_IP:7053"
-
-cp refinery/template/docker-compose.yml refinery/docker-compose.yml
-
-sed -i.bak -e "s|{MINIO_ENDPOINT}|$MINIO_ENDPOINT|g" refinery/docker-compose.yml
-sed -i.bak -e "s|{CRED_ENDPOINT}|$CRED_ENDPOINT|g" refinery/docker-compose.yml
-sed -i.bak -e "s|{LOCAL_VOLUME_POSTGRES}|$LOCAL_VOLUME_POSTGRES|g" refinery/docker-compose.yml
-sed -i.bak -e "s|{LOCAL_VOLUME_MINIO}|$LOCAL_VOLUME_MINIO|g" refinery/docker-compose.yml
-sed -i.bak -e "s|{LOCAL_VOLUME_QDRANT}|$LOCAL_VOLUME_QDRANT|g" refinery/docker-compose.yml
-
-rm refinery/*.bak
-
-#pull exec envs if not existent
-if [[ "$(docker images -q kernai/refinery-ac-exec-env:v1.3.0 2> /dev/null)" == "" ]]; then
-    docker pull kernai/refinery-ac-exec-env:v1.3.0
-fi
-if [[ "$(docker images -q kernai/refinery-lf-exec-env:v1.2.0 2> /dev/null)" == "" ]]; then
-    docker pull kernai/refinery-lf-exec-env:v1.2.0
-fi
-if [[ "$(docker images -q kernai/refinery-ml-exec-env:v1.3.0 2> /dev/null)" == "" ]]; then
-    docker pull kernai/refinery-ml-exec-env:v1.3.0
-fi
-if [[ "$(docker images -q kernai/refinery-record-ide-env:v1.2.0 2> /dev/null)" == "" ]]; then
-    docker pull kernai/refinery-record-ide-env:v1.2.0
+if [ $? -ne 0 ]; then
+    echo "Preparations failed."
+    exit 1
 fi
 
-if [ ! -f "./refinery/oathkeeper/jwks.json" ]; then
-    docker run --rm docker.io/oryd/oathkeeper:v0.38 credentials generate --alg RS256 > refinery/oathkeeper/jwks.json
-fi
-
-source wait_until_db_ready
-source alembic_fix
+echo "Preparations finsihed. Starting refinery..."
 
 docker-compose -f refinery/docker-compose.yml up -d 
 
